name: Nerima Availability (every 3 hours)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */3 * * *"   # 3時間おき

jobs:
  run-both:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Tokyo
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies (pip + Playwright)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps chromium

      - name: Run 屋内スポーツ施設
        run: |
          python main.py

      - name: Run 文化施設
        env:
          CATEGORY1_LABEL: "文化施設"
        run: |
          python main.py

      - name: Upload logs & snapshots (artifacts)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: nerima-data
          path: |
            data/**/*
            data/*.json
            data/*.txt

      # ← テストメールを一旦止める（あとで true / 削除で復活）
      - name: SMTP health check (optional)
        if: false
        env:
          AUTONERIMAGYM: ${{ secrets.AUTONERIMAGYM }}
        run: |
          # ここは secrets を環境に展開済み前提で生メール送信を試す
          python - <<'PY'
          from modules.notifier import send_mail
          print("sending test mail...")
          send_mail([{"date_iso":"2025-10-04","time":"09:00–11:00","facility":"health-check"}], dry_run=False)
          print("ok")
          PY
